name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Discourse bare repository
        uses: actions/cache@v4
        with:
          path: discourse/
          key: discourse

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate hooks analysis
        run: pnpm run build

      - name: Clean up worktrees
        run: |
          # Remove only the worktree directories, keep the bare repo for caching
          find discourse-versions -maxdepth 1 -type d ! -name "discourse-versions" ! -name ".discourse-main-repo" -exec rm -rf {} + || true
          # Clean up any other large temporary files
          npm cache clean --force || true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./web"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
